export const objectsUA = [
  [
    "Паперовий/картонний пакет",
    "Флаєр",
    "Газета",
    "Журнал",
    "Фото",
    "Конверти",
    "Нотатки",
    "Книга з м'якою обкладинкою",
    "Брошура",
    "Паперовий стакан",
    "Паперовий лоток для яєць",
    "Втулка з туалетного паперу",
  ],
  ["Склянки", "Скляні пляшки", "Скляний посуд", "Склобій"],
  [
    "Чайні пакетики",
    "Рослини",
    "Чайний осад",
    "Фрукти/овочі",
    "Креветки",
    "Кавова гуща",
    "Хліб",
    "Листя",
    "Гілка",
    "Трава",
    "Сир",
    "Квіти",
    "Яєчна шкарлупа",
  ],
  [
    "Папка",
    "Плівка",
    "Пластиковий посуд",
    "Пластиковий пакет",
    "Пакування для напоїв",
    "Тетрапак",
    "Пластикова іграшка",
    "Пластикова пляшка",
  ],
  [
    "Світлоідіодна лампа",
    "Електронний годинник",
    "Телефон",
    "Лампочка",
    "Люмінесцентна лампа",
    "Галогенна лампа",
    "Кабелі",
    "Комп'ютерне обладнання",
    "Фен",
    "Батарейки",
    "Електробритви",
  ],
  [
    "Металеві посудини",
    "Алюмінієва фольга",
    "Лезо",
    "Металева бляшанка",
    "Фольга",
    "Металева коробка",
  ],
];
export const objectsEN = [
  [
    "Packages",
    "Flyers",
    "Newsletter",
    "Journal",
    "Photos",
    "Letters",
    "Notes",
    "Books",
    "Posters",
    "Paper cup",
    "Egg carton",
    "Toilet paper",
  ],
  ["Glass", "Bottles", "Glass dishes", "Cullet"],
  [
    "Tee bags",
    "Plants",
    "Fruits/Vegetables",
    "Fish",
    "Coffe",
    "Bread",
    "Leafs",
    "Trees",
    "Grass",
    "Cheese",
    "Flowers",
    "Eggs",
  ],
  [
    "File folders",
    "Foil",
    "Plastic dishes",
    "Plastic bag",
    "Drinks packages",
    "Tetrapack",
    "Toys",
    "Plastic bottles",
  ],
  [
    "LEDs",
    "Watches",
    "Phones",
    "Lamp",
    "Glowing Lamp",
    "Cabels",
    "Computers",
    "Hair dryers",
    "Batteries",
  ],
  [
    "Aluminum dishes",
    "Aluminum foil",
    "Blades",
    "Metal cans",
    "Foil",
    "Metal boxes",
  ],
];
